POST http://localhost:8081/authenticator/person/authenticate 
Content-Type: application/json

{
    "email": "nicolas@udea.edu.co",
    "password": "nicolas"
}

###

GET http://localhost:8080/project/project/listAll
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoicHJvZmVzb3IiLCJpZCI6NSwic3ViIjoic2FtdWVsQHVkZWEuZWR1LmNvIiwiaWF0IjoxNzYxNzE1Mjk5LCJleHAiOjE3NjE3MTYxOTl9.bgY6-7c6S4IrRZ-bXO9zHJsIOysjyTVZQAzcc0nJljQ

###

POST http://localhost:8080/authenticator/person/authenticate 
Content-Type: application/json

{
    "email": "geraldin@udea.edu.co",
    "password": "geraldin"
}

###

POST http://localhost:8080/project/project/save
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiZXN0dWRpYW50ZSIsImlkIjo0LCJzdWIiOiJnZXJhbGRpbkB1ZGVhLmVkdS5jbyIsImlhdCI6MTc2MTcxNTQ5NSwiZXhwIjoxNzYxNzE2Mzk1fQ.C_0roTB7ytPVNBlGQPEjCkjxrhh7kofxlVwQrsYwd1c
Content-Type: application/json

{
    "name":"Proyecto 3",
    "description": "Proyecto bases de datos",
    "deadline": "2025-12-10",
    "team": {
        "id": 1
    }
}

###

POST http://localhost:8080/project/project/save
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiZXN0dWRpYW50ZSIsImlkIjo0LCJzdWIiOiJnZXJhbGRpbkB1ZGVhLmVkdS5jbyIsImlhdCI6MTc2MTY2NzMwOCwiZXhwIjoxNzYxNjY4MjA4fQ.UjCXh89Bl5zWPHoW5M6QMzP2b_zWSl5wvLROHTuSNLI
Content-Type: application/json

{
    "name":"Proyecto 3",
    "description": "Proyecto bases de datos",
    "deadline": "2025-12-10",
    "team": {
        "id": 6
    }
}

###

GET http://localhost:8080/project/project/message
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiZXN0dWRpYW50ZSIsImlkIjo0LCJzdWIiOiJnZXJhbGRpbkB1ZGVhLmVkdS5jbyIsImlhdCI6MTc2MTcxNTQ5NSwiZXhwIjoxNzYxNzE2Mzk1fQ.C_0roTB7ytPVNBlGQPEjCkjxrhh7kofxlVwQrsYwd1c


###

POST http://localhost:8080/authenticator/person/authenticate 
Content-Type: application/json

{
    "email": "samuel@udea.edu.co",
    "password": "samuel"
}

###

DELETE http://localhost:8082/project/task/delete/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiZXN0dWRpYW50ZSIsImlkIjo0LCJzdWIiOiJnZXJhbGRpbkB1ZGVhLmVkdS5jbyIsImlhdCI6MTc2MTcxNTQ5NSwiZXhwIjoxNzYxNzE2Mzk1fQ.C_0roTB7ytPVNBlGQPEjCkjxrhh7kofxlVwQrsYwd1c

###

PUT http://localhost:8082/project/task/updateState/3/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiZXN0dWRpYW50ZSIsImlkIjo0LCJzdWIiOiJnZXJhbGRpbkB1ZGVhLmVkdS5jbyIsImlhdCI6MTc2MTcxNTQ5NSwiZXhwIjoxNzYxNzE2Mzk1fQ.C_0roTB7ytPVNBlGQPEjCkjxrhh7kofxlVwQrsYwd1c

###

GET http://localhost:8082/project/team/getStudentsName/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiZXN0dWRpYW50ZSIsImlkIjo0LCJzdWIiOiJnZXJhbGRpbkB1ZGVhLmVkdS5jbyIsImlhdCI6MTc2MTcxNTQ5NSwiZXhwIjoxNzYxNzE2Mzk1fQ.C_0roTB7ytPVNBlGQPEjCkjxrhh7kofxlVwQrsYwd1c

