POST http://localhost:8082/project/project/save 
Content-Type: application/json

{
    "name":"Proyecto 1",
    "description": "Proyecto bases de datos",
    "deadline": "2025-12-10",
    "team": {
        "id": 1
    }
}

###
POST http://localhost:8082/project/task/save
Content-Type: application/json

{
    "title":"Esquemas",
    "description": "Probando diferentes esquemas",
    "deadline":"2025-12-10",
    "responsible":"Karen",
    "project": {
        "id": 7
    }
}

###

POST http://localhost:8082/project/objective/save 
Content-Type: application/json

{
    "description":"aprender mucho sobre esquemas",
    "project": {
        "id": 7
    }
}

###

GET http://localhost:8082/project/task/listAll

###

GET http://localhost:8082/project/project/listAll
###

DELETE http://localhost:8082/project/task/delete/27

###

PUT http://localhost:8082/project/task/update
Content-Type: application/json

{
    "id": 2,
    "title":"hola",
    "description": "Prueba final",
    "deadline":"2025-12-10",
    "responsible": "Karen",
    "project": {
        "id": 1
    }
}

###

PUT http://localhost:8082/project/task/updateState/2/2

### 

GET http://localhost:8082/project/team/getStudentsName/1

###
