POST http://localhost:8080/project/save 
Content-Type: application/json

{
    "name":"Proyecto 1",
    "description": "Proyecto 1 - descripción",
    "deadline": "2025-12-10",
    "team": {
        "id": 224
    }
}

###
POST http://localhost:8080/task/save
Content-Type: application/json

{
    "title":"Valora",
    "description": "Valorar la vida",
    "deadline":"2025-12-10",
    "responsible":"Karen",
    "project": {
        "id": 15
    }
}

###

POST http://localhost:8080/objective/save 
Content-Type: application/json

{
    "description":"vivir la vida",
    "project": {
        "id": 15
    }
}

###

GET http://localhost:8080/task/listAll

###

GET http://localhost:8080/project/listAll
###

DELETE http://localhost:8080/task/delete/27

###

PUT http://localhost:8080/task/update
Content-Type: application/json

{
    "id": 29,
    "title":"Tarea 1",
    "description": "Prueba final",
    "deadline":"2025-12-10",
    "responsible": "Camila",
    "project": {
        "id": 15
    }
}